//! The HTDemucs short-time Fourier contract, ported from Wavey's
//! on-device `StemSeparator.swift`.
//!
//! The Core ML HTDemucs package that ships in the app does not contain the
//! STFT. Wavey runs it in Swift on either side of the model: a forward
//! transform into `spectral_magnitude`, and an inverse applied to the model's
//! frequency branch before it is summed with the time branch. This crate is
//! that same transform in Rust, so a server can feed the model the identical
//! tensor the phone does.
//!
//! It is a faithful port, quirks included, because the model was trained
//! against them:
//!
//! * The forward transform is the true `rfft` of a periodic-Hann-windowed,
//!   reflect-padded signal, scaled by `1/sqrt(fft_size)`.
//! * The Nyquist bin is **dropped** (Demucs keeps `fft_size / 2` bins).
//! * The inverse is the true inverse DFT with the Nyquist bin forced to zero.
//! * Overlap-add accumulates the squared window over **every** inverse frame,
//!   including the two leading and two trailing zero frames that carry no
//!   audio. That is not a detail to tidy away: it changes the normalisation
//!   at the edges and is part of the contract.
//!
//! Parity with the Swift/vDSP implementation is proven by
//! `tests/parity.rs`, which reads a golden vector generated by
//! `tools/oracle-stft`.

use rustfft::num_complex::Complex;
use rustfft::FftPlanner;

/// The geometry of one STFT pass. The shipped values live in
/// [`Geometry::CONTRACT`]; [`Geometry::SMALL`] exists so a golden vector fits
/// in the repository.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Geometry {
    pub sample_rate: u32,
    pub channels: usize,
    pub fft_size: usize,
    pub hop_size: usize,
    pub bins: usize,
    pub frames: usize,
    pub segment: usize,
}

impl Geometry {
    /// The contract Wavey's Core ML model was converted against.
    pub const CONTRACT: Geometry = Geometry {
        sample_rate: 44_100,
        channels: 2,
        fft_size: 4_096,
        hop_size: 1_024,
        bins: 2_048,
        frames: 336,
        segment: 343_980,
    };

    /// A geometry small enough to commit as a golden vector.
    pub const SMALL: Geometry = Geometry {
        sample_rate: 44_100,
        channels: 2,
        fft_size: 64,
        hop_size: 16,
        bins: 32,
        frames: 8,
        segment: 120,
    };

    /// Samples of reflect padding in front of the segment.
    pub const fn pad_left(&self) -> usize {
        self.hop_size / 2 * 3
    }

    /// Samples of reflect padding behind it, chosen so the padded signal is
    /// exactly the frames the model is fed.
    pub const fn pad_right(&self) -> usize {
        self.pad_left() + self.frames * self.hop_size - self.segment
    }

    pub const fn padded_len(&self) -> usize {
        self.segment + self.pad_left() + self.pad_right()
    }

    /// The inverse transform reconstructs `frames + 4` windows: two zero
    /// frames either side of the audio.
    pub const fn inverse_frames(&self) -> usize {
        self.frames + 4
    }

    pub const fn inverse_trim(&self) -> usize {
        self.fft_size / 2 + self.pad_left()
    }

    pub const fn inverse_raw_len(&self) -> usize {
        (self.inverse_frames() - 1) * self.hop_size + self.fft_size
    }
}

/// One channel's spectrum, laid out `[bin][frame]` as the model expects.
#[derive(Clone, Debug, PartialEq)]
pub struct Spectrum {
    pub real: Vec<f32>,
    pub imaginary: Vec<f32>,
}

/// The periodic Hann window, exactly as `StemSeparator.swift` builds it:
/// computed in `f64`, stored as `f32`.
pub fn hann(fft_size: usize) -> Vec<f32> {
    (0..fft_size)
        .map(|index| {
            (0.5 * (1.0 - (2.0 * std::f64::consts::PI * index as f64 / fft_size as f64).cos()))
                as f32
        })
        .collect()
}

/// Reflect padding that excludes the boundary sample, matching the Swift
/// `reflectPad` and `torch.nn.functional.pad(mode = "reflect")`.
pub fn reflect_pad(signal: &[f32], left: usize, right: usize) -> Vec<f32> {
    assert!(
        signal.len() >= 2,
        "reflect padding needs at least two samples"
    );
    let count = signal.len();
    let mut output = vec![0.0f32; count + left + right];
    for index in 0..left {
        output[index] = signal[left - index];
    }
    output[left..(left + count)].copy_from_slice(signal);
    for index in 0..right {
        output[left + count + index] = signal[count - 2 - index];
    }
    output
}

/// The forward transform of one channel, over its own padded signal.
pub fn forward(
    signal: &[f32],
    geometry: &Geometry,
    window: &[f32],
    planner: &mut FftPlanner<f32>,
) -> Spectrum {
    assert_eq!(
        signal.len(),
        geometry.segment,
        "forward input is one segment"
    );
    assert_eq!(window.len(), geometry.fft_size, "window length");
    let padded = reflect_pad(signal, geometry.pad_left(), geometry.pad_right());
    let fft = planner.plan_fft_forward(geometry.fft_size);
    let mut buffer = vec![Complex::new(0.0f32, 0.0); geometry.fft_size];
    let plane = geometry.bins * geometry.frames;
    let mut real = vec![0.0f32; plane];
    let mut imaginary = vec![0.0f32; plane];
    for frame in 0..geometry.frames {
        let start = frame * geometry.hop_size;
        for sample in 0..geometry.fft_size {
            buffer[sample] = Complex::new(padded[start + sample] * window[sample], 0.0);
        }
        fft.process(&mut buffer);
        for (bin, value) in buffer.iter().enumerate().take(geometry.bins) {
            let index = bin * geometry.frames + frame;
            real[index] = value.re;
            imaginary[index] = value.im;
        }
    }
    Spectrum { real, imaginary }
}

/// The four planes the model reads as `spectral_magnitude`:
/// `[left.real, left.imaginary, right.real, right.imaginary]`, scaled by
/// `1/sqrt(fft_size)`.
pub fn spectral_input(
    left: &[f32],
    right: &[f32],
    geometry: &Geometry,
    window: &[f32],
    planner: &mut FftPlanner<f32>,
) -> Vec<f32> {
    let plane = geometry.bins * geometry.frames;
    let mut output = vec![0.0f32; 4 * plane];
    for (channel, signal) in [left, right].into_iter().enumerate() {
        let spectrum = forward(signal, geometry, window, planner);
        output[(channel * 2 * plane)..((channel * 2 + 1) * plane)].copy_from_slice(&spectrum.real);
        output[((channel * 2 + 1) * plane)..((channel * 2 + 2) * plane)]
            .copy_from_slice(&spectrum.imaginary);
    }
    let scale = 1.0 / (geometry.fft_size as f32).sqrt();
    for value in output.iter_mut() {
        *value *= scale;
    }
    output
}

/// The inverse transform of one channel's `[bin][frame]` spectrum, trimmed
/// back to one segment. This is what is applied to the model's frequency
/// branch; multiply the result by `sqrt(fft_size)` before summing it with the
/// time branch, exactly as `StemSeparator.swift` does.
pub fn inverse(
    spectrum: &Spectrum,
    geometry: &Geometry,
    window: &[f32],
    planner: &mut FftPlanner<f32>,
) -> Vec<f32> {
    let plane = geometry.bins * geometry.frames;
    assert_eq!(spectrum.real.len(), plane, "spectrum length");
    assert_eq!(spectrum.imaginary.len(), plane, "spectrum length");
    let total = geometry.inverse_frames();
    let raw_len = geometry.inverse_raw_len();
    let mut output = vec![0.0f32; raw_len];
    let mut weights = vec![0.0f32; raw_len];
    let fft = planner.plan_fft_inverse(geometry.fft_size);
    let mut buffer = vec![Complex::new(0.0f32, 0.0); geometry.fft_size];
    let normalise = 1.0 / geometry.fft_size as f32;

    for frame in 0..total {
        for value in buffer.iter_mut() {
            *value = Complex::new(0.0, 0.0);
        }
        // The audio frames sit two positions in; the rest are zero frames that
        // still contribute their window weight.
        if frame >= 2 && frame < 2 + geometry.frames {
            let source = frame - 2;
            buffer[0] = Complex::new(spectrum.real[source], 0.0);
            for bin in 1..geometry.bins {
                let index = bin * geometry.frames + source;
                let value = Complex::new(spectrum.real[index], spectrum.imaginary[index]);
                buffer[bin] = value;
                buffer[geometry.fft_size - bin] = value.conj();
            }
        }
        fft.process(&mut buffer);
        let start = frame * geometry.hop_size;
        for sample in 0..geometry.fft_size {
            let value = buffer[sample].re * normalise * window[sample];
            output[start + sample] += value;
            weights[start + sample] += window[sample] * window[sample];
        }
    }

    for index in 0..raw_len {
        if weights[index] > 0.000_000_01 {
            output[index] /= weights[index];
        }
    }
    let trim = geometry.inverse_trim();
    output[trim..(trim + geometry.segment)].to_vec()
}

/// A forward/inverse pair bound to one geometry, holding the window and FFT
/// plan so a long run is not re-planning per frame.
pub struct Stft {
    geometry: Geometry,
    window: Vec<f32>,
    planner: FftPlanner<f32>,
}

impl Stft {
    pub fn new(geometry: Geometry) -> Self {
        Self {
            geometry,
            window: hann(geometry.fft_size),
            planner: FftPlanner::new(),
        }
    }

    pub fn geometry(&self) -> Geometry {
        self.geometry
    }

    pub fn window(&self) -> &[f32] {
        &self.window
    }

    pub fn forward(&mut self, signal: &[f32]) -> Spectrum {
        forward(signal, &self.geometry, &self.window, &mut self.planner)
    }

    pub fn spectral_input(&mut self, left: &[f32], right: &[f32]) -> Vec<f32> {
        spectral_input(left, right, &self.geometry, &self.window, &mut self.planner)
    }

    pub fn inverse(&mut self, spectrum: &Spectrum) -> Vec<f32> {
        inverse(spectrum, &self.geometry, &self.window, &mut self.planner)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_geometry_is_self_consistent() {
        let geometry = Geometry::CONTRACT;
        assert_eq!(geometry.pad_left(), 1_536);
        assert_eq!(geometry.pad_right(), 1_620);
        assert_eq!(geometry.padded_len(), 347_136);
        assert_eq!(
            geometry.padded_len(),
            (geometry.frames - 1) * geometry.hop_size + geometry.fft_size
        );
        assert_eq!(geometry.inverse_frames(), 340);
        assert_eq!(geometry.inverse_trim(), 3_584);
    }

    #[test]
    fn reflect_pad_matches_torch_semantics() {
        let signal: Vec<f32> = (0..8).map(|value| value as f32).collect();
        let padded = reflect_pad(&signal, 2, 2);
        assert_eq!(
            padded,
            vec![2.0, 1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 6.0, 5.0]
        );
    }
}
